name: Build and push image
on:
  push:
    branches: ["main"]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cs2304-f23-app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/cs2304-f23-app:${{ github.sha }}
      - name: Configure kubectl
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy the updated image
        run: kubectl set image deployment/website website=${{ secrets.DOCKERHUB_USERNAME}}/cs2304-f23-app:${{ github.sha }}
